$ErrorActionPreference = "Stop"

$projectRoot = [IO.Path]::GetFullPath((Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)))
$releaseRoot = [IO.Path]::GetFullPath((Join-Path $projectRoot "release"))
$packageName = "TingYiNotes-0.2.0-macOS-build"
$target = [IO.Path]::GetFullPath((Join-Path $releaseRoot $packageName))
$archive = [IO.Path]::GetFullPath((Join-Path $releaseRoot ($packageName + ".zip")))
$releasePrefix = $releaseRoot.TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar

if (-not $target.StartsWith($releasePrefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Release target escaped the release directory: $target"
}

New-Item -ItemType Directory -Force -Path $releaseRoot | Out-Null
if (Test-Path -LiteralPath $target) {
    Remove-Item -LiteralPath $target -Recurse -Force
}
if (Test-Path -LiteralPath $archive) {
    Remove-Item -LiteralPath $archive -Force
}
New-Item -ItemType Directory -Path $target | Out-Null

foreach ($directory in @("assets", "macos", "src")) {
    Copy-Item -LiteralPath (Join-Path $projectRoot $directory) -Destination $target -Recurse
}

foreach ($file in @(".env.example", "pyproject.toml", "README.md")) {
    Copy-Item -LiteralPath (Join-Path $projectRoot $file) -Destination $target
}

# Copy the Chinese-named release notes and macOS commands without embedding
# non-ASCII path literals, keeping compatibility with Windows PowerShell 5.
Get-ChildItem -LiteralPath $projectRoot -File -Filter "*.md" |
    Where-Object { $_.Name -ne "README.md" } |
    Copy-Item -Destination $target
Get-ChildItem -LiteralPath $projectRoot -File -Filter "*macOS.command" |
    Copy-Item -Destination $target

# Never ship bytecode or metadata generated by a developer checkout.
Get-ChildItem -LiteralPath $target -Directory -Recurse -Force |
    Where-Object { $_.Name -in @("__pycache__", "tingyiji_notes.egg-info", "classnote_translator.egg-info") } |
    Sort-Object FullName -Descending |
    Remove-Item -Recurse -Force
Get-ChildItem -LiteralPath $target -File -Recurse -Force -Filter "*.pyc" |
    Remove-Item -Force

Compress-Archive -LiteralPath $target -DestinationPath $archive -CompressionLevel Optimal
Write-Host "Release build package created: $archive"
